import type { BuffsObject } from '@core/shared/types';

const templateBuffs = {
	worldbuffs: [
		{
			id: 355363,
			name: 'Rallying Cry of the Dragonslayer',
			path: 'inv_misc_head_dragon_01',
		},
		{
			id: 24425,
			name: 'Spirit of Zandalar',
			path: 'ability_creature_poison_05',
		},
		{
			id: 23768,
			name: "Sayge's Dark Fortune of Damage",
			path: 'inv_misc_orb_02',
		},
		{
			id: 355366,
			name: "Warchief's Blessing",
			path: 'spell_arcane_teleportorgrimmar',
		},
		{
			id: 1304690,
			name: 'Songflower Serenade',
			path: 'spell_holy_mindvision',
			minlevel: 50,
		},
		{
			id: 22817,
			name: "Fengus' Ferocity",
			path: 'spell_nature_undyingstrength',
			minlevel: 50,
		},
		{
			id: 1304751,
			name: "Slip'kik's Savvy",
			path: 'spell_holy_lesserheal02',
			minlevel: 50,
		},
		{
			id: 1304753,
			name: "Mol'dar's Moxie",
			path: 'spell_nature_massteleport',
			minlevel: 50,
		},
	],
	raidbuffs: [
		{
			id: 24932,
			name: 'Leader of the Pack',
			path: 'spell_nature_unyeildingstamina',
			minlevel: 40,
		},
		{
			id: 5232,
			name: 'Mark of the Wild',
			path: 'spell_nature_regeneration',
			minlevel: 10,
			maxlevel: 19,
		},
		{
			id: 6756,
			name: 'Mark of the Wild',
			path: 'spell_nature_regeneration',
			minlevel: 20,
			maxlevel: 29,
		},
		{
			id: 5234,
			name: 'Mark of the Wild',
			path: 'spell_nature_regeneration',
			minlevel: 30,
			maxlevel: 39,
		},
		{
			id: 8907,
			name: 'Mark of the Wild',
			path: 'spell_nature_regeneration',
			minlevel: 40,
			maxlevel: 49,
		},
		{
			id: 9884,
			name: 'Mark of the Wild',
			path: 'spell_nature_regeneration',
			minlevel: 50,
			maxlevel: 59,
		},
		{
			id: 9885,
			name: 'Mark of the Wild',
			path: 'spell_nature_regeneration',
			minlevel: 60,
			child: 17055,
		},
		{
			id: 17055,
			name: 'Improved Mark of the Wild',
			path: 'spell_nature_regeneration',
			mod: 1.35,
			ischild: true,
		},
		{
			id: 19506,
			name: 'Trueshot Aura',
			path: 'ability_trueshot',
			minlevel: 40,
			maxlevel: 49,
		},
		{
			id: 20905,
			name: 'Trueshot Aura',
			path: 'ability_trueshot',
			minlevel: 50,
			maxlevel: 59,
		},
		{
			id: 20906,
			name: 'Trueshot Aura',
			path: 'ability_trueshot',
			minlevel: 60,
		},
		{
			id: 20217,
			name: 'Blessing of Kings',
			path: 'spell_magic_magearmor',
			minlevel: 20,
		},
		{
			id: 19740,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 4,
			maxlevel: 11,
		},
		{
			id: 19834,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 12,
			maxlevel: 21,
		},
		{
			id: 19835,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 22,
			maxlevel: 31,
		},
		{
			id: 19836,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 32,
			maxlevel: 41,
		},
		{
			id: 19837,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 42,
			maxlevel: 51,
		},
		{
			id: 19838,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 52,
			requires: [{ name: 'aqbooks', value: 'no' }],
			child: 20048,
		},
		{
			id: 25291,
			name: 'Blessing of Might',
			path: 'spell_holy_fistofjustice',
			minlevel: 60,
			requires: [{ name: 'aqbooks', value: 'yes' }],
			child: 20048,
		},
		{
			id: 20048,
			name: 'Improved Blessing of Might',
			path: 'spell_holy_fistofjustice',
			mod: 1.2,
			ischild: true,
		},
		{
			id: 8836,
			name: 'Grace of Air Totem',
			path: 'spell_nature_invisibilitytotem',
			minlevel: 42,
			maxlevel: 55,
		},
		{
			id: 10626,
			name: 'Grace of Air Totem',
			path: 'spell_nature_invisibilitytotem',
			minlevel: 56,
			requires: [{ name: 'aqbooks', value: 'no' }],
		},
		{
			id: 25360,
			name: 'Grace of Air Totem',
			path: 'spell_nature_invisibilitytotem',
			minlevel: 60,
			requires: [{ name: 'aqbooks', value: 'yes' }],
		},
		{
			id: 8076,
			name: 'Strength of Earth Totem',
			path: 'spell_nature_earthbindtotem',
			minlevel: 10,
			maxlevel: 23,
		},
		{
			id: 8162,
			name: 'Strength of Earth Totem',
			path: 'spell_nature_earthbindtotem',
			minlevel: 24,
			maxlevel: 37,
		},
		{
			id: 8163,
			name: 'Strength of Earth Totem',
			path: 'spell_nature_earthbindtotem',
			minlevel: 38,
			maxlevel: 51,
		},
		{
			id: 10441,
			name: 'Strength of Earth Totem',
			path: 'spell_nature_earthbindtotem',
			minlevel: 52,
			requires: [{ name: 'aqbooks', value: 'no' }],
		},
		{
			id: 25362,
			name: 'Strength of Earth Totem',
			path: 'spell_nature_earthbindtotem',
			minlevel: 60,
			requires: [{ name: 'aqbooks', value: 'yes' }],
		},
	],
	consumables: [
		{
			id: 10667,
			name: 'R.O.I.D.S.',
			path: 'inv_stone_15',
			group: 'blasted',
			minlevel: 45,
		},
		{
			id: 10669,
			name: 'Ground Scorpok Assay',
			path: 'inv_misc_dust_02',
			group: 'blasted',
			minlevel: 45,
		},
		{
			id: 3160,
			name: 'Elixir of Lesser Agility',
			path: 'inv_potion_92',
			group: 'elixir',
			minlevel: 18,
			maxlevel: 49,
		},
		{
			id: 11328,
			name: 'Elixir of Agility',
			path: 'inv_potion_93',
			group: 'elixir',
			minlevel: 27,
			maxlevel: 50,
		},
		{
			id: 11334,
			name: 'Elixir of Greater Agility',
			path: 'inv_potion_94',
			group: 'elixir',
			minlevel: 41,
		},
		{
			id: 17538,
			name: 'Elixir of the Mongoose',
			path: 'inv_potion_32',
			group: 'elixir',
			minlevel: 46,
		},
		{
			id: 16323,
			name: 'Juju Power',
			path: 'inv_misc_monsterscales_11',
			group: 'str',
			minlevel: 55,
		},
		{
			id: 2367,
			name: "Elixir of Lion's Strength",
			path: 'inv_potion_56',
			group: 'str',
			minlevel: 1,
			maxlevel: 49,
		},
		{
			id: 3164,
			name: "Elixir of Ogre's Strength",
			path: 'inv_potion_57',
			group: 'str',
			minlevel: 20,
		},
		{
			id: 8212,
			name: 'Elixir of Giant Growth',
			path: 'inv_potion_10',
			group: 'str',
			minlevel: 8,
			maxlevel: 49,
		},
		{
			id: 8120,
			name: 'Scroll of Strength III',
			path: 'inv_scroll_02',
			group: 'str',
			minlevel: 40,
			maxlevel: 49,
		},
		{
			id: 11405,
			name: 'Elixir of Giants',
			path: 'inv_potion_61',
			group: 'str',
			minlevel: 41,
		},
		{
			id: 16329,
			name: 'Juju Might',
			path: 'inv_misc_monsterscales_07',
			group: 'ap',
			minlevel: 55,
		},
		{
			id: 17038,
			name: 'Winterfall Firewater',
			path: 'inv_potion_92',
			group: 'ap',
			minlevel: 45,
		},
		{
			id: 24799,
			name: 'Smoked Desert Dumplings',
			path: 'inv_misc_food_64',
			group: 'food',
			minlevel: 54,
		},
		{
			id: 18192,
			name: 'Grilled Squid',
			path: 'inv_misc_fish_13',
			group: 'food',
			minlevel: 41,
		},
		{
			id: 18125,
			name: 'Blessed Sunfruit',
			path: 'inv_misc_food_41',
			group: 'food',
			minlevel: 45,
		},
	],
	debuffs: [
		{
			id: 7386,
			name: 'Sunder Armor',
			path: 'ability_warrior_sunder',
			group: 'sunder',
			minlevel: 10,
			maxlevel: 21,
		},
		{
			id: 7405,
			name: 'Sunder Armor',
			path: 'ability_warrior_sunder',
			group: 'sunder',
			minlevel: 22,
			maxlevel: 33,
		},
		{
			id: 8380,
			name: 'Sunder Armor',
			path: 'ability_warrior_sunder',
			group: 'sunder',
			minlevel: 34,
			maxlevel: 45,
		},
		{
			id: 11596,
			name: 'Sunder Armor',
			path: 'ability_warrior_sunder',
			group: 'sunder',
			minlevel: 46,
			maxlevel: 57,
		},
		{
			id: 11597,
			name: 'Sunder Armor',
			path: 'ability_warrior_sunder',
			group: 'sunder',
			minlevel: 58,
		},
		{
			id: 8647,
			name: 'Expose Armor',
			path: 'ability_warrior_riposte',
			group: 'sunder',
			minlevel: 14,
			maxlevel: 25,
		},
		{
			id: 8649,
			name: 'Expose Armor',
			path: 'ability_warrior_riposte',
			group: 'sunder',
			minlevel: 26,
			maxlevel: 35,
		},
		{
			id: 8650,
			name: 'Expose Armor',
			path: 'ability_warrior_riposte',
			group: 'sunder',
			minlevel: 36,
			maxlevel: 45,
		},
		{
			id: 11197,
			name: 'Expose Armor',
			path: 'ability_warrior_riposte',
			group: 'sunder',
			minlevel: 46,
			maxlevel: 55,
		},
		{
			id: 11198,
			name: 'Expose Armor',
			path: 'ability_warrior_riposte',
			group: 'sunder',
			minlevel: 56,
			child: 14169,
		},
		{
			id: 770,
			name: 'Faerie Fire',
			path: 'spell_nature_faeriefire',
			minlevel: 18,
			maxlevel: 29,
		},
		{
			id: 778,
			name: 'Faerie Fire',
			path: 'spell_nature_faeriefire',
			minlevel: 30,
			maxlevel: 41,
		},
		{
			id: 9749,
			name: 'Faerie Fire',
			path: 'spell_nature_faeriefire',
			minlevel: 42,
			maxlevel: 53,
		},
		{
			id: 9907,
			name: 'Faerie Fire',
			path: 'spell_nature_faeriefire',
			minlevel: 54,
		},
		{
			id: 704,
			name: 'Curse of Recklessness',
			path: 'spell_shadow_unholystrength',
			minlevel: 14,
			maxlevel: 27,
		},
		{
			id: 7658,
			name: 'Curse of Recklessness',
			path: 'spell_shadow_unholystrength',
			minlevel: 28,
			maxlevel: 41,
		},
		{
			id: 7659,
			name: 'Curse of Recklessness',
			path: 'spell_shadow_unholystrength',
			minlevel: 42,
			maxlevel: 55,
		},
		{
			id: 11717,
			name: 'Curse of Recklessness',
			path: 'spell_shadow_unholystrength',
			minlevel: 56,
		},
		{
			id: 9176,
			name: 'Torch of Holy Flame',
			path: 'inv_staff_05',
			minlevel: 20,
		},
		{
			id: 11371,
			name: 'Gift of Arthas',
			path: 'inv_potion_28',
			minlevel: 41,
		},
	],
	others: [
		{
			id: 15852,
			name: 'Dragonbreath Chili',
			path: 'inv_drink_17',
			minlevel: 35,
		},

		{
			id: 5665,
			name: 'Bogling Root',
			path: 'inv_misc_herb_07',
			minlevel: 1,
		},
		{
			id: 27723,
			name: 'Dark Desire',
			path: 'inv_valentineschocolate04',
		},
		{
			id: 29332,
			name: 'Fire-toasted Bun',
			path: 'inv_misc_food_11',
		},
		{
			id: 29338,
			name: 'Fire Festival Fury',
			path: 'inv_misc_summerfest_brazierorange',
		},
		{
			id: 29232,
			name: 'Fungal Bloom',
			path: 'spell_nature_unyeildingstamina',
			minlevel: 60,
		},
		{
			id: 27666,
			name: 'Darnassus Gift of Friendship',
			group: 'blasted',
			path: 'inv_misc_gift_02',
			minlevel: 1,
		},
		{
			id: 17626,
			name: 'Flask of the Titans',
			path: 'inv_potion_62',
			minlevel: 50,
			group: 'flask',
		},
		{
			id: 17629,
			name: 'Flask of Chromatic Resistance',
			path: 'inv_potion_48',
			minlevel: 50,
			group: 'flask',
		},
		{
			id: 16326,
			name: 'Juju Ember',
			path: 'inv_misc_monsterscales_15',
			minlevel: 55,
		},
		{
			id: 11364,
			name: 'Magic Resistance Potion',
			path: 'inv_potion_16',
			minlevel: 32,
		},
		{
			id: 19900,
			name: 'Fire Resistance Aura',
			path: 'spell_fire_sealoffire',
			minlevel: 60,
		},
	],
} as BuffsObject;

export default templateBuffs;
